id = "rvt"
name = "Reach Variant Tool"
version = "0.1.0"
schema_version = 1
authors = ["Gage Howe"]
description = "Syntax highlighting and completions for Reach Variant Tool scripts."
repository = "https://github.com/GageHowe/zed-rvt"

[grammars.rvt]
repository = "https://github.com/GageHowe/zed-rvt"
commit = "6678df25d5c3271f99986f7dc046d69cc653827a"

[language_servers.rvt_lsp]
name = "RVT Language Server"
language = "Reach Variant Tool"
