id = "rvt"
name = "Reach Variant Tool"
version = "0.1.0"
schema_version = 1
authors = ["Gage Howe"]
description = "Syntax highlighting, indentation, outline support, and snippets for Reach Variant Tool scripts."
repository = "https://github.com/GageHowe/zed-rvt"

[grammars.rvt]
repository = "https://github.com/GageHowe/zed-rvt"
commit = "e19aa7dbdba69fc709c174e1704493a37432f703"
